name: App

on:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE'
  workflow_dispatch: # Tambahan agar Anda bisa memicu build secara manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # LANGKAH "Write key" DIHAPUS TOTAL DARI SINI

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        id: buildWithGradle
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || true
          echo 'android.sdk.channel=3' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          
          # Perintah diubah menjadi assembleDebug agar tidak butuh Keystore
          ./gradlew :manager:assembleDebug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: shizuku-debug-apk
          # Path disesuaikan untuk mengambil file Debug APK
          path: "manager/build/outputs/apk/debug/*.apk"
          compression-level: 9
