name: App (Unsigned Release APK)

on:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE'
  workflow_dispatch: # Memungkinkan Anda menekan tombol run secara manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        id: buildWithGradle
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || true
          echo 'android.sdk.channel=3' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          
          # PERINTAH DIUBAH MENJADI assembleRelease
          # Karena tidak ada konfigurasi keystore, ini akan mengompilasi mode Release (termasuk optimasi C++) 
          # dan menghasilkan APK berstatus "unsigned".
          ./gradlew :manager:assembleRelease

      - name: Upload Unsigned Release APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: shizuku-release-unsigned
          # Mengambil folder hasil build release
          path: "manager/build/outputs/apk/release/*.apk"
          compression-level: 9
